# Generated by Django 6.0.5 on 2026-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='api_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
