# Generated by Django 6.0.5 on 2026-06-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_consumer', '0002_alter_broker_api_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
