# Generated by Django 5.2.15 on 2026-06-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_consumer', '0003_alter_script_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tick',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
